spring:
  mvc:
    problemdetails:
      enabled: true

  mongodb:
    uri: mongodb://mongo:Kkvhm8ZsqXhXbBadnheNblw6vHqr4DRrUp6KMZsj6tL0jNtf@966fd2df-afff-4d1f-a0d6-074ca9420d23.asia-south1.firestore.goog:443/program-mongo-db?loadBalanced=true&tls=true&authMechanism=SCRAM-SHA-256&retryWrites=false

server:
  port: 0

eureka:
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}